#!/bin/bash -e
options=("${@:1:$(($# - 1))}")                  # Everything in "$@" except the last argument
target="${!#}"                                  # The last argument from "$@"

# Get user
usertest="${target%%:*}"
if [ ! "${usertest/@/}" = "${usertest}" ]; then # user is included in the target
    user="${target%%@*}"                        # Get user
    target="${target#*@}"                       # Strip out user
fi

# Get default path from ssh config file defined as SendEnv WorkingDirectory:path, e.g.
#
#  SendEnv WorkingDirectory:/data/www/my-site/htdocs
#
default_path=$(ssh -G "$target" | grep -i "WorkingDirectory:" | cut -d: -f2)

# Get hostname and path
if [ "${target::1}" = "[" ]; then               # Syntax:  [user@]\[hostname\]:path
    remote="${target%\]*}]"
    path="${target#*\]}"
    if [ -z "${path}" ]; then
	exec ssh "$@"
    fi
    path="${path:1}"
else                                            # Syntax:  [user@]hostname:path
    remote="${target%%:*}"
    path="${target#*:}"
    if [ "${path}" = "${target}" ]; then
      if [ -z "${default_path}" ]; then
	exec ssh "$@"
      else
        path=$default_path
      fi
    fi
fi

# Construct target argument for ssh
if [ ! "${usertest/@/}" = "${usertest}" ]; then # user is included in the target
    remote="${user}@${remote}"                  # Reattach user
fi

path="${path/\'/\'\\\'\'}"
exec ssh -t "${options[@]}" "${remote}" "cd '${path}'; exec \$SHELL -l"
